/*
	test_kernel.cpp - does the GPU kernel agree with the CPU path?

	Two checks, over every scenario in kernel_test_common.h:

	  1. host    ChromaVRGradient3D_Kernel.h compiled as ordinary C++ (via
	             ChromaVRGradient3D_GPU.h) against chroma::shadePixel. Runs
	             anywhere; proves the kernel *logic* matches, in float.
	  2. OpenCL  (when built with CHROMA_TEST_OPENCL and an OpenCL device is
	             present) the very same kernel text the plug-in embeds, built
	             by this machine's OpenCL driver and run on the GPU, against
	             the same reference. Proves the text compiles as OpenCL C and
	             that the GPU gets the same picture.

	Build and run (Windows, from src/): .\build.ps1 -Test
	Host check only, anywhere:
	    g++ -std=c++17 -O2 -I.. test_kernel.cpp -o test_kernel && ./test_kernel
*/

#include "kernel_test_common.h"
#include "ChromaVRGradient3D_KernelSource.h"	/* generated by the build: kChromaKernelBody */

#include <cstdint>
#include <cstdio>
#include <cstdlib>

#if defined(CHROMA_TEST_OPENCL)
	#if defined(_WIN32)
		#define WIN32_LEAN_AND_MEAN
		#include <windows.h>
	#else
		#include <dlfcn.h>
	#endif
#endif

using namespace ktest;

static int g_fail = 0;

/* ------------------------------------------------------------------ */
/*  1. the kernel compiled as C++                                      */
/* ------------------------------------------------------------------ */

static void runHost(const std::vector<Scenario>& all) {
	std::printf("\n-- kernel as C++ (float) vs chroma::shadePixel (double) --\n");
	for (const Scenario& s : all) {
		const std::vector<float> want = reference(s);
		const std::vector<float> got  = hostKernel(s);
		if (!report("", s, compare(s, got, want))) ++g_fail;
	}
}

/* ------------------------------------------------------------------ */
/*  2. the kernel through OpenCL                                       */
/* ------------------------------------------------------------------ */

#if defined(CHROMA_TEST_OPENCL)

/*	The plug-in module (ChromaVRGradient3D_OpenCL.cpp, linked in) does the
	compile and the launch. The test only needs enough OpenCL of its own to
	make a device, a queue and two buffers, and to read the result back.	*/
namespace cl {

typedef int32_t  cl_int;
typedef uint32_t cl_uint;
typedef uint64_t cl_bitfield;
typedef struct _cl_platform_id*   cl_platform_id;
typedef struct _cl_device_id*     cl_device_id;
typedef struct _cl_context*       cl_context;
typedef struct _cl_command_queue* cl_command_queue;
typedef struct _cl_mem*           cl_mem;
typedef struct _cl_event*         cl_event;

#if defined(_WIN32)
	#define CLAPI __stdcall
#else
	#define CLAPI
#endif

typedef cl_int           (CLAPI *P_clGetPlatformIDs)(cl_uint, cl_platform_id*, cl_uint*);
typedef cl_int           (CLAPI *P_clGetDeviceIDs)(cl_platform_id, cl_bitfield, cl_uint, cl_device_id*, cl_uint*);
typedef cl_int           (CLAPI *P_clGetDeviceInfo)(cl_device_id, cl_uint, size_t, void*, size_t*);
typedef cl_context       (CLAPI *P_clCreateContext)(const intptr_t*, cl_uint, const cl_device_id*, void*, void*, cl_int*);
typedef cl_command_queue (CLAPI *P_clCreateCommandQueue)(cl_context, cl_device_id, cl_bitfield, cl_int*);
typedef cl_mem           (CLAPI *P_clCreateBuffer)(cl_context, cl_bitfield, size_t, void*, cl_int*);
typedef cl_int           (CLAPI *P_clEnqueueReadBuffer)(cl_command_queue, cl_mem, cl_uint, size_t, size_t, void*, cl_uint, const cl_event*, cl_event*);
typedef cl_int           (CLAPI *P_clFinish)(cl_command_queue);
typedef cl_int           (CLAPI *P_clReleaseMemObject)(cl_mem);
typedef cl_int           (CLAPI *P_clReleaseCommandQueue)(cl_command_queue);
typedef cl_int           (CLAPI *P_clReleaseContext)(cl_context);

static const cl_bitfield DEVICE_TYPE_GPU   = 1 << 2;
static const cl_bitfield MEM_READ_ONLY     = 1 << 2;
static const cl_bitfield MEM_WRITE_ONLY    = 1 << 1;
static const cl_bitfield MEM_COPY_HOST_PTR = 1 << 5;
static const cl_uint     DEVICE_NAME       = 0x102B;

struct Api {
	P_clGetPlatformIDs       GetPlatformIDs = nullptr;
	P_clGetDeviceIDs         GetDeviceIDs = nullptr;
	P_clGetDeviceInfo        GetDeviceInfo = nullptr;
	P_clCreateContext        CreateContext = nullptr;
	P_clCreateCommandQueue   CreateCommandQueue = nullptr;
	P_clCreateBuffer         CreateBuffer = nullptr;
	P_clEnqueueReadBuffer    EnqueueReadBuffer = nullptr;
	P_clFinish               Finish = nullptr;
	P_clReleaseMemObject     ReleaseMemObject = nullptr;
	P_clReleaseCommandQueue  ReleaseCommandQueue = nullptr;
	P_clReleaseContext       ReleaseContext = nullptr;
	bool ok = false;
};

template <typename T> static void get(void* lib, const char* name, T* out) {
#if defined(_WIN32)
	*out = reinterpret_cast<T>(GetProcAddress(static_cast<HMODULE>(lib), name));
#else
	*out = reinterpret_cast<T>(dlsym(lib, name));
#endif
}

static Api load() {
	Api a;
#if defined(_WIN32)
	void* lib = LoadLibraryA("OpenCL.dll");
#else
	void* lib = dlopen("/System/Library/Frameworks/OpenCL.framework/OpenCL", RTLD_NOW);
#endif
	if (!lib) return a;
	get(lib, "clGetPlatformIDs",      &a.GetPlatformIDs);
	get(lib, "clGetDeviceIDs",        &a.GetDeviceIDs);
	get(lib, "clGetDeviceInfo",       &a.GetDeviceInfo);
	get(lib, "clCreateContext",       &a.CreateContext);
	get(lib, "clCreateCommandQueue",  &a.CreateCommandQueue);
	get(lib, "clCreateBuffer",        &a.CreateBuffer);
	get(lib, "clEnqueueReadBuffer",   &a.EnqueueReadBuffer);
	get(lib, "clFinish",              &a.Finish);
	get(lib, "clReleaseMemObject",    &a.ReleaseMemObject);
	get(lib, "clReleaseCommandQueue", &a.ReleaseCommandQueue);
	get(lib, "clReleaseContext",      &a.ReleaseContext);
	a.ok = a.GetPlatformIDs && a.GetDeviceIDs && a.GetDeviceInfo && a.CreateContext && a.CreateCommandQueue &&
		   a.CreateBuffer && a.EnqueueReadBuffer && a.Finish && a.ReleaseMemObject && a.ReleaseCommandQueue &&
		   a.ReleaseContext;
	return a;
}

}	/* namespace cl */

static void runOpenCL(const std::vector<Scenario>& all) {
	std::printf("\n-- kernel through OpenCL vs chroma::shadePixel --\n");

	cl::Api api = cl::load();
	if (!api.ok) { std::printf("  skip  no OpenCL runtime on this machine\n"); return; }

	/* first GPU device on any platform */
	cl::cl_platform_id platforms[8];
	cl::cl_uint nplat = 0;
	if (api.GetPlatformIDs(8, platforms, &nplat) != 0 || nplat == 0) {
		std::printf("  skip  no OpenCL platforms\n"); return;
	}
	cl::cl_device_id device = nullptr;
	for (cl::cl_uint i = 0; i < nplat && !device; ++i) {
		cl::cl_uint n = 0;
		cl::cl_device_id d = nullptr;
		if (api.GetDeviceIDs(platforms[i], cl::DEVICE_TYPE_GPU, 1, &d, &n) == 0 && n > 0) device = d;
	}
	if (!device) { std::printf("  skip  no OpenCL GPU device\n"); return; }

	char name[256] = { 0 };
	api.GetDeviceInfo(device, cl::DEVICE_NAME, sizeof name - 1, name, nullptr);
	std::printf("  device: %s\n", name);

	cl::cl_int err = 0;
	cl::cl_context context = api.CreateContext(nullptr, 1, &device, nullptr, nullptr, &err);
	if (!context) { std::printf("  FAIL  clCreateContext (%d)\n", err); ++g_fail; return; }
	cl::cl_command_queue queue = api.CreateCommandQueue(context, device, 0, &err);
	if (!queue) { std::printf("  FAIL  clCreateCommandQueue (%d)\n", err); ++g_fail; api.ReleaseContext(context); return; }

	/* compile exactly what the plug-in compiles */
	const std::string source = ChromaAssembleKernelSource(kChromaOpenCLPrelude, kChromaKernelBody, kChromaOpenCLEntry);
	std::string log;
	void* handle = ChromaOpenCL_Setup(context, device, source, &log);
	if (!handle) {
		std::printf("  FAIL  kernel did not compile as OpenCL C:\n%s\n", log.c_str());
		++g_fail;
		api.ReleaseCommandQueue(queue);
		api.ReleaseContext(context);
		return;
	}
	std::printf("  ok    kernel compiled as OpenCL C (%zu bytes of source)\n", source.size());

	for (const Scenario& s : all) {
		const size_t dst_bytes = static_cast<size_t>(s.w) * s.h * 4 * sizeof(float);
		cl::cl_mem src = api.CreateBuffer(context, cl::MEM_READ_ONLY | cl::MEM_COPY_HOST_PTR,
										  s.src.size() * sizeof(float), const_cast<float*>(s.src.data()), &err);
		cl::cl_mem dst = api.CreateBuffer(context, cl::MEM_WRITE_ONLY, dst_bytes, nullptr, &err);
		if (!src || !dst) { std::printf("  FAIL  %s: buffers\n", s.name.c_str()); ++g_fail; continue; }

		std::vector<float> got(static_cast<size_t>(s.w) * s.h * 4, -99.0f);
		bool ran = ChromaOpenCL_Render(handle, queue, src, dst, &s.gp);
		if (ran) {
			api.Finish(queue);
			ran = api.EnqueueReadBuffer(queue, dst, 1, 0, dst_bytes, got.data(), 0, nullptr, nullptr) == 0;
		}
		api.ReleaseMemObject(src);
		api.ReleaseMemObject(dst);

		if (!ran) { std::printf("  FAIL  %s: render call failed\n", s.name.c_str()); ++g_fail; continue; }
		if (!report("", s, compare(s, got, reference(s)))) ++g_fail;
	}

	ChromaOpenCL_Teardown(handle);
	api.ReleaseCommandQueue(queue);
	api.ReleaseContext(context);
}

#endif	/* CHROMA_TEST_OPENCL */

int main() {
	const std::vector<Scenario> all = scenarios();
	std::printf("%zu scenarios, %d x %d\n", all.size(), all[0].w, all[0].h);

	runHost(all);
#if defined(CHROMA_TEST_OPENCL)
	runOpenCL(all);
#endif

	std::printf("\n%s\n", g_fail ? "FAILED" : "all passed");
	return g_fail ? 1 : 0;
}
