/*
	test_kernel_metal.mm - the kernel through Metal, on this Mac's GPU,
	against the CPU reference. The macOS half of test_kernel.cpp's OpenCL
	check: the very text the plug-in embeds, compiled by the Metal framework
	via the plug-in's own module (ChromaVRGradient3D_Metal.mm, linked in).

	Built and run by ./build-mac.sh --test.
*/

#include "kernel_test_common.h"
#include "ChromaVRGradient3D_KernelSource.h"	/* generated by the build: kChromaKernelBody */

#import <Foundation/Foundation.h>
#import <Metal/Metal.h>

#include <cstdio>

using namespace ktest;

int main() {
	int fail = 0;
	@autoreleasepool {
		const std::vector<Scenario> all = scenarios();
		std::printf("%zu scenarios, %d x %d\n\n-- kernel through Metal vs chroma::shadePixel --\n",
			all.size(), all[0].w, all[0].h);

		id<MTLDevice> device = MTLCreateSystemDefaultDevice();
		if (!device) { std::printf("  skip  no Metal device\n"); return 0; }
		std::printf("  device: %s\n", [[device name] UTF8String]);

		id<MTLCommandQueue> queue = [device newCommandQueue];

		const std::string source = ChromaAssembleKernelSource(kChromaMetalPrelude, kChromaKernelBody, kChromaMetalEntry);
		std::string log;
		void* handle = ChromaMetal_Setup((void*)device, source, &log);
		if (!handle) {
			std::printf("  FAIL  kernel did not compile as Metal:\n%s\nFAILED\n", log.c_str());
			return 1;
		}
		std::printf("  ok    kernel compiled as Metal (%zu bytes of source)\n", source.size());

		for (const Scenario& s : all) {
			const size_t dst_bytes = static_cast<size_t>(s.w) * s.h * 4 * sizeof(float);
			id<MTLBuffer> src = [device newBufferWithBytes:s.src.data()
													length:s.src.size() * sizeof(float)
												   options:MTLResourceStorageModeShared];
			id<MTLBuffer> dst = [device newBufferWithLength:dst_bytes options:MTLResourceStorageModeShared];

			bool ran = ChromaMetal_Render(handle, (void*)device, (void*)queue, (void*)src, (void*)dst, &s.gp);
			if (ran) {
				/*	The module commits without waiting, as it does in AE. Work on
					a queue runs in order, so an empty command buffer behind it
					finishing means ours has.								*/
				id<MTLCommandBuffer> fence = [queue commandBuffer];
				[fence commit];
				[fence waitUntilCompleted];
			}

			if (!ran) { std::printf("  FAIL  %s: render call failed\n", s.name.c_str()); ++fail; }
			else {
				std::vector<float> got(static_cast<size_t>(s.w) * s.h * 4);
				std::memcpy(got.data(), [dst contents], dst_bytes);
				if (!report("", s, compare(s, got, reference(s)))) ++fail;
			}
			[src release];
			[dst release];
		}

		ChromaMetal_Teardown(handle);
		[queue release];
		[device release];
	}
	std::printf("\n%s\n", fail ? "FAILED" : "all passed");
	return fail ? 1 : 0;
}
