#!/usr/bin/env bash
#
# build-mac.sh - build ChromaVRGradient3D.plugin (After Effects effect, macOS)
#
#   ./build-mac.sh              # build a universal bundle
#   ./build-mac.sh --install    # build, then copy into After Effects
#   ./build-mac.sh --clean      # wipe intermediates first
#   ./build-mac.sh --test       # build, then build and run the tests
#
# The Windows counterpart is build.ps1 beside this file. Same stages -
# resource, kernel, compile, assemble - but macOS wants a bundle rather than a
# flat .aex, and the PiPL goes through Rez instead of PiPLtool + rc:
#
#   ChromaVRGradient3D.plugin/
#     Contents/
#       Info.plist                        eFKT / FXTC, which is what marks it
#       PkgInfo                           an After Effects effect
#       MacOS/ChromaVRGradient3D          universal arm64 + x86_64 Mach-O
#       Resources/ChromaVRGradient3D.rsrc the compiled PiPL
#
# GPU: Metal, always. The kernel is compiled by the Metal framework at run
# time from text embedded in the binary, so there is no shader build step
# and one bundle serves Apple Silicon and Intel alike. If Metal is off or
# the kernel fails to compile, the effect renders on the CPU as before.
#
# Like build.ps1, nothing here is hardcoded to one machine: the SDK is found by
# looking for AE_Effect.h, and After Effects by taking the highest-numbered
# install. Set AE_SDK or AE_APP to override either.

set -euo pipefail

NAME="ChromaVRGradient3D"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC="$HERE"
OBJ="$SRC/obj-mac"
OUT="$(cd "$HERE/.." && pwd)"
BUNDLE="$OUT/$NAME.plugin"
VERSION="1.3"

step() { printf '\033[36m==> %s\033[0m\n' "$1"; }
warn() { printf '\033[33m    %s\033[0m\n' "$1"; }
fail() { printf '\033[31m!!! %s\033[0m\n' "$1" >&2; exit 1; }

DO_INSTALL=""
DO_TEST=""
for arg in "$@"; do
    case "$arg" in
        --clean)   rm -rf "$OBJ" "$BUNDLE" ;;
        --install) DO_INSTALL=1 ;;
        --test)    DO_TEST=1 ;;
        *)         fail "unknown option: $arg" ;;
    esac
done

# --- locate the SDK ----------------------------------------------------
if [ -z "${AE_SDK:-}" ]; then
    for guess in "$HOME/Documents/AE_SDK"/*/Examples "$HOME/AE_SDK"/*/Examples \
                 /Applications/AE_SDK/*/Examples; do
        if [ -f "$guess/Headers/AE_Effect.h" ]; then AE_SDK="$guess"; break; fi
    done
fi
[ -n "${AE_SDK:-}" ] && [ -f "$AE_SDK/Headers/AE_Effect.h" ] \
    || fail "After Effects SDK not found. Set AE_SDK to its Examples folder."

REZ="$(xcrun --find Rez 2>/dev/null)" || fail "Rez not found - install Xcode."
MACSDK="$(xcrun --show-sdk-path)"

echo "    SDK : $AE_SDK"
echo "    Rez : $REZ"
echo "    Out : $BUNDLE"

mkdir -p "$OBJ" \
         "$BUNDLE/Contents/MacOS" \
         "$BUNDLE/Contents/Resources"

# --- 1. the PiPL, through Rez -----------------------------------------
# The .r pulls in AE_General.r, and Rez needs the Carbon headers for the
# resource types the SDK's own .r files are written against.
step "Compiling the PiPL resource"
CARBON="$MACSDK/System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers"
"$REZ" -o "$BUNDLE/Contents/Resources/$NAME.rsrc" \
    -d __MACH__ -useDF \
    -i "$AE_SDK/Headers" \
    -i "$AE_SDK/Resources" \
    -i "$CARBON" \
    -i "$MACSDK/System/Library/Frameworks" \
    "$SRC/${NAME}PiPL.r" \
    || fail "Rez failed on the PiPL"
[ -s "$BUNDLE/Contents/Resources/$NAME.rsrc" ] || fail "Rez produced an empty .rsrc"

# --- 2. embed the GPU kernel source ------------------------------------
# Metal compiles the kernel from text at run time, so the kernel header goes
# into the binary as a byte array. `od` rather than xxd or python: it is in
# every macOS install and needs no extra tooling.
step "Embedding the kernel source"
KERNEL_SRC="$SRC/${NAME}_Kernel.h"
KERNEL_HDR="$OBJ/${NAME}_KernelSource.h"
[ -f "$KERNEL_SRC" ] || fail "missing kernel source: $KERNEL_SRC"
{
    echo "/* Generated by build-mac.sh from ${NAME}_Kernel.h - do not edit, do not commit. */"
    echo "static const char kChromaKernelBody[] = {"
    tr -d '\r' < "$KERNEL_SRC" | od -An -v -tu1 | tr -s ' \n' ' ' | sed 's/^ *//; s/ *$//; s/  */, /g' | fold -w 120 -s
    echo ","
    echo "0};"
} > "$KERNEL_HDR"
[ -s "$KERNEL_HDR" ] || fail "could not write $KERNEL_HDR"

# --- 3. compile and link the bundle ------------------------------------
# One clang++ call: a handful of small translation units and a separate
# compile step would buy nothing but a longer script. The .mm is picked up as
# Objective-C++ by its extension; it is the only file that speaks to Metal.
step "Compiling and linking (arm64 + x86_64)"
clang++ \
    -std=c++17 -O2 -fvisibility=hidden -Wall \
    -arch arm64 -arch x86_64 \
    -mmacosx-version-min=11.0 \
    -bundle \
    -DCHROMA_HAS_METAL=1 \
    -I"$SRC" \
    -I"$OBJ" \
    -I"$AE_SDK/Headers" \
    -I"$AE_SDK/Headers/SP" \
    -I"$AE_SDK/Util" \
    -I"$AE_SDK/Resources" \
    "$SRC/$NAME.cpp" \
    "$SRC/${NAME}_Metal.mm" \
    "$AE_SDK/Util/AEGP_SuiteHandler.cpp" \
    "$AE_SDK/Util/MissingSuiteError.cpp" \
    "$AE_SDK/Util/Smart_Utils.cpp" \
    -framework CoreFoundation \
    -framework CoreServices \
    -framework Foundation \
    -framework Metal \
    -o "$BUNDLE/Contents/MacOS/$NAME" \
    || fail "compile/link failed"

# --- 4. bundle metadata -------------------------------------------------
# eFKT / FXTC is what tells After Effects this bundle is an effect; without
# it the plug-in is simply never looked at. Matches the SDK's own samples.
step "Writing bundle metadata"
cat > "$BUNDLE/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleExecutable</key>
	<string>$NAME</string>
	<key>CFBundleIdentifier</key>
	<string>london.chroma.aftereffects.$NAME</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>$NAME</string>
	<key>CFBundlePackageType</key>
	<string>eFKT</string>
	<key>CFBundleSignature</key>
	<string>FXTC</string>
	<key>CFBundleShortVersionString</key>
	<string>$VERSION</string>
	<key>LSRequiresCarbon</key>
	<true/>
	<key>NSAppleScriptEnabled</key>
	<string>No</string>
	<key>NSHumanReadableCopyright</key>
	<string>Chroma</string>
</dict>
</plist>
PLIST
printf 'eFKTFXTC' > "$BUNDLE/Contents/PkgInfo"

# Ad-hoc signature. Unsigned bundles are refused on Apple Silicon, and the
# failure is silent - the effect simply never appears.
step "Ad-hoc signing"
codesign --force --sign - --timestamp=none "$BUNDLE" 2>/dev/null \
    || echo "    codesign failed - the effect may not load on Apple Silicon"

step "Built $BUNDLE"
lipo -archs "$BUNDLE/Contents/MacOS/$NAME" | sed 's/^/    architectures: /'
ls -la "$BUNDLE/Contents/MacOS/$NAME" | awk '{print "    " $5 " bytes"}'
echo "    GPU: Metal, CPU fallback"

# --- 5. optional tests ---------------------------------------------------
# test_math and preview need only the maths header. test_kernel runs the GPU
# kernel compiled as C++ against the double-precision reference;
# test_kernel_metal then compiles the very same text with Metal on this
# machine's GPU and checks that agrees too.
if [ -n "$DO_TEST" ]; then
    step "Building and running the tests"
    TOBJ="$OBJ/tests"
    mkdir -p "$TOBJ"
    TFLAGS=(-std=c++17 -O2 -Wall -I"$SRC" -I"$OBJ" -DCHROMA_HAS_METAL=1)
    clang++ "${TFLAGS[@]}" "$SRC/tests/test_math.cpp"   -o "$TOBJ/test_math"   || fail "could not build test_math"
    clang++ "${TFLAGS[@]}" "$SRC/tests/preview.cpp"     -o "$TOBJ/preview"     || fail "could not build preview"
    clang++ "${TFLAGS[@]}" "$SRC/tests/test_kernel.cpp" -o "$TOBJ/test_kernel" || fail "could not build test_kernel"
    clang++ "${TFLAGS[@]}" "$SRC/tests/test_kernel_metal.mm" "$SRC/${NAME}_Metal.mm" \
        -framework Foundation -framework Metal \
        -o "$TOBJ/test_kernel_metal" || fail "could not build test_kernel_metal"

    failed=0
    for t in test_math preview test_kernel test_kernel_metal; do
        if (cd "$SRC/tests" && "$TOBJ/$t"); then
            printf '\033[32m    %s passed\033[0m\n' "$t"
        else
            warn "$t FAILED"
            failed=$((failed + 1))
        fi
    done
    [ "$failed" -eq 0 ] || fail "$failed test program(s) failed"
fi

# --- 6. optional install -------------------------------------------------
if [ -n "$DO_INSTALL" ]; then
    if [ -z "${AE_APP:-}" ]; then
        AE_APP="$(ls -d /Applications/Adobe\ After\ Effects\ * 2>/dev/null | sort | tail -1)"
    fi
    [ -n "$AE_APP" ] || fail "After Effects not found. Set AE_APP."
    DEST="$AE_APP/Plug-ins/Effects"
    step "Installing to $DEST"
    # The Effects folder is root-owned; sudo only when a plain copy is refused.
    if mkdir -p "$DEST" 2>/dev/null && rm -rf "$DEST/$NAME.plugin" 2>/dev/null && cp -R "$BUNDLE" "$DEST/" 2>/dev/null; then
        echo "    installed. Restart After Effects."
    else
        warn "plain copy refused - retrying with sudo"
        sudo mkdir -p "$DEST"
        sudo rm -rf "$DEST/$NAME.plugin"
        sudo cp -R "$BUNDLE" "$DEST/"
        echo "    installed. Restart After Effects."
    fi
fi
